; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Thu Sep 03 2020 13:53:09 GMT-0600 (Central Standard Time)
M280 P0 S90 ; retract BLTouch

