; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool on Wed Feb 07 2018 13:21:45 GMT-0600 (CST)
M98 P"0:/sys/ZSpeedsPrint.g"	; Load Z speeds for printing
M98 P"0:/sys/CurrentsPrint.g"	; Load print motor currents
G1 R1 Z5 F10000 ; go to 5mm above position of the last print move
G1 R1          ; go back to the last print move
G11		; unretract

