; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool on Wed Feb 07 2018 13:21:45 GMT-0600 (CST)
G10		; retract filament
G91		; relative positioning
G1 Z5 F600	; lift Z by 5mm
G90		; absolute positioning
G1 X10 Y10 F10000	; go to X=0 Y=0