name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
- x0rtrunks
body:
- type: markdown
  attributes:
    value: |
      # STOP!
      ### Before posting a bug report here, you must start a discussion on Duet3D forums. This is to help reduce duplicates and solve configuration issues.
      https://forum.duet3d.com/categories

      ### Before posting your issue, please review the following sources to check if your question has already been reported and answered.

      #### Have you checked the documentation?
      https://duet3d.dozuki.com/

      #### Have you checked the GCODE Wiki?
      https://duet3d.dozuki.com/Wiki/Gcode

      #### Have you checked the firmware release notes?
      RRF2: https://github.com/Duet3D/RepRapFirmware/blob/dev/WHATS_NEW.md
      RRF3: https://github.com/Duet3D/RepRapFirmware/blob/v3-dev/WHATS_NEW_RRF3.md

      #### Have you searched the forums?
      https://forum.duet3d.com/search

      #### If this is a Beta firmware release, have you checked the Beta Firmware Forum?
      https://forum.duet3d.com/category/30/beta-firmware

      #### Have you searched the existing issues on GitHub?
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
