; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sat Mar 07 2020 23:07:21 GMT+0100 (CET)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


