; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sat Mar 07 2020 23:07:21 GMT+0100 (CET)
G91              ; relative positioning
G1 Z5 F1400 S2   ; lower Z relative to current position
G1 S1 Y230 F6000 ; move quickly to Y axis endstop and stop there (first pass)
G1 Y-5 F1000     ; go back a few mm
G1 S1 Y230 F900  ; move slowly to Y axis endstop once more (second pass)
G1 Z-5 F1400 S2  ; raise Z again
G90              ; absolute positioning

