; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sat Mar 07 2020 23:07:21 GMT+0100 (CET)
; Wait for set temperatures to be reached
M116 P0

