; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Mon May 06 2019 00:09:49 GMT-0600 (Central Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


