; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.2 on Sun Nov 10 2019 17:04:46 GMT-0600 (Central Standard Time)
M280 P64 S90 ; retract BLTouch

