; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Mon May 06 2019 00:09:50 GMT-0600 (Central Standard Time)

