; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Mon May 06 2019 00:09:51 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
M116 P0

