; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Aug 24 2020 23:25:01 GMT-0600 (Central Standard Time)
M280 P0 S10 ; deploy BLTouch

