; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v2 on Sun May 05 2019 17:25:18 GMT-0600 (Central Standard Time)

G10 ; retract
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X10 Y10 F6000 ; go to X=10 Y=10

