; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Sun May 05 2019 17:25:19 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
M116 P0

