; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun Mar 20 2022 16:46:49 GMT+0000 (Greenwich Mean Time)
M42 P24 S0
M42 P26 S0
M42 P25 S255
M83            ; relative extruder moves
G1 E-10 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z50 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X150 Y0 F6000 ; go to X=150 Y=0

