; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun Mar 20 2022 16:46:49 GMT+0000 (Greenwich Mean Time)

