; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun Mar 20 2022 16:46:49 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0

