; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sat Sep 12 2020 23:38:42 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
M116 P1

