; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Wed Jan 12 2022 21:37:09 GMT+0000 (Greenwich Mean Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


