; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Wed Jan 12 2022 21:37:09 GMT+0000 (Greenwich Mean Time)
; insert codes for deploying the Z probe here

