; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Wed Jan 12 2022 22:37:56 GMT+0000 (Greenwich Mean Time)
; insert codes for retracting the Z probe here

