; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Wed Jan 12 2022 22:48:38 GMT+0000 (Greenwich Mean Time)
M280 P0 S90 ; retract BLTouch

