; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Wed Jan 12 2022 21:37:09 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0

